stages:
  - Docker
  - Trigger
  - Build

# Buil jobs for manual and automatic
# -------------------------------------
# These jobs will run the docker image creation for atlaslatex
# automatically for the master branch and manual for the rest
build_image:
  stage: Docker
  variables:
    TO: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  tags:
    - docker-image-build
  script:
  - echo building image

# These jobs will trigger the docker image creation for pogitlab in the gitlab-integration project
# automatically for the master branch and manual for the rest
trigger-pogitlab:
  stage: Trigger
  only: 
    - master@atlas-physics-office/atlaslatex
  script:
      - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.cern.ch/api/v4/projects/19489/trigger/pipeline

# this automatically builds the exotics template and sends it to a publicly accessible spac
# https://gitlab.cern.ch/atlas-physics-office/atlaslatex/-/jobs/artifacts/master/file/mydocument.pdf?job=build_NOTE
build_NOTE:
  image: gitlab-registry.cern.ch/meehan/atlaslatex-image:master
  stage: Build
  except:
    - master@atlas-physics-office/atlaslatex
  script:
    - make newnote BASENAME=mydocument
    - make 
  artifacts:
    paths:
      - mydocument.pdf
    expire_in: 1 year

# this automatically builds the PAPER template
# https://gitlab.cern.ch/atlas-physics-office/atlaslatex/-/jobs/artifacts/master/file/mydocument.pdf?job=build_PAPER
build_PAPER:
  image: gitlab-registry.cern.ch/meehan/atlaslatex-image:master
  stage: Build
  except:
    - master@atlas-physics-office/atlaslatex
  script:
    - make newpaper BASENAME=mydocument
    - make 
  artifacts:
    paths:
      - mydocument.pdf
    expire_in: 1 year

# this automatically builds the exotics template and sends it to a publicly accessible space
# https://gitlab.cern.ch/atlas-physics-office/atlaslatex/-/jobs/artifacts/master/file/template/EXOT/EXOT_template.pdf?job=build_EXOT
build_EXOT:
  image: gitlab-registry.cern.ch/meehan/atlaslatex-image:master
  stage: Build
  except:
    - master@atlas-physics-office/atlaslatex
  script:
    - cd template/EXOT
    - make
  artifacts:
    paths:
      - template/EXOT/EXOT_template.pdf
    expire_in: 1 year