stages:
    - Docker
    - Trigger
variables:
  FROM: gitlab-registry.cern.ch/atlas-physics-office/gitlab-integration/pogitlab 
  TO: $FROM 

# Buil jobs for manual and automatic
# -------------------------------------
pogitlab:
  stage: Docker
  only:
  - master
  tags:
    - docker-image-build
  script:
    - echo "Preparing docker image"

pogitlab-manual:
  stage: Docker
  when: manual
  except:
  - master
  tags:
    - docker-image-build
  script:
    - echo "Preparing docker image"

# This job will trigger the pipeline in gitlab-integration to update the docker image accordingly
build_docs:
  stage: Trigger
  script:
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.cern.ch/api/v4/projects/19489/trigger/pipeline
