stages:
  - Docker
  - Trigger
  - Build
  - Transfer

# Buil jobs for manual and automatic
# -------------------------------------
# These jobs will run the docker image creation for atlaslatex
# automatically for the master branch and manual for the rest
al-docker:
  variables:
    DOCKER_FILE: ".config/Dockerfile"
  stage: Docker
  only:
    - master@atlas-physics-office/atlaslatex
  tags:
    - docker-image-build
  script:
    - echo "Preparing docker image"

# These jobs will trigger the docker image creation for pogitlab in the gitlab-integration project
# automatically for the master branch and manual for the rest
trigger-pogitlab:
  stage: Trigger
  only: 
    - master@atlas-physics-office/atlaslatex
  script:
      - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.cern.ch/api/v4/projects/19489/trigger/pipeline

# this automatically builds the exotics template and sends it to a publicly accessible spac
build:
  image: thomasweise/docker-texlive-full:latest
  stage: Build
  except:
    - master@atlas-physics-office/atlaslatex
  script:
    - cd template/EXOT
    - make
  artifacts:
    paths:
      - template/EXOT/EXOT_template.pdf
    expire_in: 1 week
      
# transfer to web-viewable space
transfer:
  image: atlas/analysisbase:21.2.75
  stage: Transfer
  dependencies: 
    - build
  script:
    - source /home/atlas/release_setup.sh
    - echo $SERVICE_PASS | kinit $CERN_USER@CERN.CH
    - xrdcp EXOT_template.pdf root://eoshome.cern.ch//eos/user/m/meehan/www/EXOT_template.pdf
    