stages:
  - Docker
  - Trigger
  - Build

# Buil jobs for manual and automatic
# -------------------------------------
# These jobs will run the docker image creation for atlaslatex
# automatically for the master branch and manual for the rest
al-docker:
  variables:
    DOCKER_FILE: ".config/Dockerfile"
  stage: Docker
  only:
    - master@atlas-physics-office/atlaslatex
  tags:
    - docker-image-build
  script:
    - echo "Preparing docker image"

# These jobs will trigger the docker image creation for pogitlab in the gitlab-integration project
# automatically for the master branch and manual for the rest
trigger-pogitlab:
  stage: Trigger
  only: 
    - master@atlas-physics-office/atlaslatex
  script:
      - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.cern.ch/api/v4/projects/19489/trigger/pipeline

# this automatically builds the exotics template and sends it to a publicly accessible spac
build:
  image: gitlab-registry.cern.ch/meehan/atlaslatex-image:master
  stage: Build
  except:
    - master@atlas-physics-office/atlaslatex
  script:
    - cd template/EXOT
    - make
  artifacts:
    paths:
      - template/EXOT/EXOT_template.pdf
    expire_in: 1 year