stages:
    - Docker
    - Trigger
variables:
  FROM: gitlab-registry.cern.ch/atlas-physics-office/gitlab-integration/pogitlab 
  TO: $FROM 

# Buil jobs for manual and automatic
# -------------------------------------
# These jobs will run the docker image creation for atlaslatex
# automatically for the master branch and manual for the rest
al-docker:
  stage: Docker
  only:
  - master
  tags:
    - docker-image-build
  script:
    - echo "Preparing docker image"

al-dockr-manual:
  stage: Docker
  when: manual
  except:
    - master
  tags:
    - docker-image-build
  script:
    - echo "Preparing docker image"

# These jobs will trigger the docker image creation for pogitlab in the gitlab-integration project
# automatically for the master branch and manual for the rest
trigger-pogitlab:
  stage: Trigger
  only:
    - master
  script:
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.cern.ch/api/v4/projects/19489/trigger/pipeline
